#pragma once

struct ComputeSatellite;  // forward declaration

/// Thermal simulation using Stefan-Boltzmann radiative cooling.
/// On a Raspberry Pi, also reads the real CPU temperature as
/// an analog for servicer thermal state.
class ThermalModel {
public:
    /// Compute new temperature for a satellite over time step dt.
    /// @return Updated temperature in Celsius.
    static double compute_temperature(
        const ComputeSatellite& sat,
        double dt,
        double current_temp_c
    );

    /// Read real CPU temperature from a Raspberry Pi.
    /// @return Temperature in Celsius, or -1.0 if unavailable.
    static double read_pi_cpu_temp();

    // ── Component heat calculations ──

    /// Solar heat absorbed (W). Zero when in eclipse.
    static double solar_heat_input(double absorptivity, double area_m2, bool in_eclipse);

    /// Radiative heat dissipated to space via Stefan-Boltzmann law (W).
    static double radiative_dissipation(
        double emissivity,
        double area_m2,
        double temp_k,
        double radiator_efficiency
    );

    /// Heat generated by compute workload (W).
    static double compute_heat(double compute_load, int num_gpus, double heat_per_gpu);

    /// Simplified eclipse check based on orbital angle.
    static bool is_in_eclipse(double orbital_angle);
};
